### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "Muhammed",
  "lastName": "AJ",
  "gender": "Male",
  "dateOfBirth": "2000-01-01",
  "email": "test101@example.com",
  "password": "mynamei123s",
  "phoneNumber": "+970569059979",
  "role": "Customer",
  "status": "Inactive"
}

### Verify Code
POST http://localhost:3000/auth/verify
Content-Type: application/json

{
  "email": "test101@example.com",
  "code": "35585"
}

### Resend Code
POST http://localhost:3000/auth/resend-code
Content-Type: application/json

{
  "email": "test100@example.com"
}